hello and buttons files
deshipu/microbit-micropython-pl pull request #5
Opened 2017-11-10 19:58 UTC by WojtekReu

2017-11-27 19:53 UTC, deshipu requested changes
Dziękuję za tłumaczenie i przepraszam, że tak długo to trwało. Jak zwykle, staram się być tak drobiazgowy, jak to tylko możliwe i dla każdej rzeczy, która wydaje mi się podejrzana podaję przykład, który wydaje mi się lepszy. Oczywiście krytykuję tłumaczenie, nie autora, więc proszę się nie obrażać.

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Jak dotychczas utworzyliśmy kod umożliwiający urządzeniu pokazywanie czegoś.
robienie czegoś

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +zdarzenia. Zdarzenia i wszystkie dane jakie dostaje urządzenie nazywamy *wejściem*.
Wprowadzasz dodatkowe pojęcie, którego nie ma w oryginalnym tekście i które jest zbędne. Moim zdaniem wystarczyłoby napisać: "Musimy też jednak umożliwić urządzeniu reagowanie. To, na co ono reaguje nazywamy *wejściem*."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Najprostszym sposobem na dostarczenie informacji na wejściu są dwa przyciski na urządzeniu micro:bit,
Najpierw "wydarzenia", teraz "informacja" oraz "na wejściu" — nowe pojęcia, które ani nie były zdefiniowane, ani nie ma ich w oryginalnym tekście. Co byś powiedział na:

"Najłatwiejszą metodą dostarczenia *wejścia* są dwa przyciski, oznaczone ``A`` i ``B``. Musimy jakoś zmusić MicroPython do reagowania na ich naciśnięcie."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Cały skrypt jest uśpiony przez 10 000 milisekund (czyli 10 sekund) a po tym
Dlaczego "cały"? "Ten skrypt śpi przez 10 000 milisekund"

Przecinek przed "a".

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +pomysłów:
koncepcji

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +#. *Funkcja* ``sleep`` usypia microbit na pewną ilość milisekund. Jeżeli
liczbę, milisekundy są policzalne

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +#. Istnieje obiekt nazwany ``button_a`` i on pozwala ci pobrać wartość
o nazwie

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +#. Istnieje obiekt nazwany ``button_a`` i on pozwala ci pobrać wartość
"i on pozwala" →", który pozwala".

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +#. Istnieje obiekt nazwany ``button_a`` i on pozwala ci pobrać wartość
Albo prościej, "Obiekt ``button_a`` pozwala ci pobrać liczbę naciśnięć przycisku...". Nie musimy kopiować rozwlekłej angielskiej gramatyki.

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +*zagnieżdżenie* - programistyczny odpowiednik rosyjskiej lalki - matrioszka.
"rosyjskiej lalki - matrioszka" → "rosyjskiej matrioszki" – to słowo się odmienia i chyba jest wystarczająco znane w Polsce, żeby nie trzeba było tłumaczyć, że to lalka

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Teraz, gdy Python wie już ile razy został wciśnięty przycisk, to przetworzy
"to" wydaje mi się tu zbędne

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Teraz, gdy Python wie już ile razy został wciśnięty przycisk, to przetworzy
"skonwertuje"?

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +W końcu Python wie, że ma wyświetlić przesuwający się tekst na ekranie::
"co ma wyświetlić na ekranie"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Może ci się wydawać, że to jest mnóstwo pracy ale MicroPython robi to
przecinek przed "ale"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Często potrzebujesz aby program poczekał na jakieś zdarzenie. Aby uzyskać
"Często chcesz, aby"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +naciśnięcie przycisku.
To zdanie jest taką kalką z angielskiej gramatyki, że nawet nie da się go zrozumieć. Nie bójmy się przestawiać fragmentów tekstu, jeśli gramatyka tego wymaga. Ale tu możemy dać coś w rodzaju:

"Żeby to uzyskać, musisz zamknąć w pętli kawałek kodu definiujący jak reagować na oczekiwane zdarzenia, takie jak naciśnięcie przycisku."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Aby utworzyć pętle w Pythonie użyj słowa kluczowego ``while`` (ang. dopóki). To sprawdza czy
przecinek przed "użyj", ale moim zdaniem lepiej by brzmiało: "Pętle w Pythonie tworzymy przy użyciu polecania ``while`` (ang. dopóki)."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Aby utworzyć pętle w Pythonie użyj słowa kluczowego ``while`` (ang. dopóki). To sprawdza czy
"To sprawdza" →"Sprawdza ono"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +coś jest ``True`` (ang. prawdziwe). Jeżeli tak jest, to uruchamia *blok kodu* zwany *zawartością*
Mnie uczyli, że zawartość pętli to jest jej "ciało", ale może moi profesorowie kopiowali dosłownie z angielskiego.

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +a wtedy wykona się pozostała część kodu.
"i przechodzi do dalszej części kodu."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +zrobienia napisaną na kartce papieru. Pewnie będzie wyglądało to tak::
"Może to wyglądać tak::"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +        Wyjmij drabinę z sąsiednich drzwi
To jest frazal. "Pożycz drabinę od sąsiada".

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +To oczywiste, że główne zadania są podzielone na podrzędne zadania, które
"Oczywiście główne zadania..."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +zaczynają się od *akapitu* (wcięcie) (ang. indent) poniżej głównego zadania, do którego
"na podrzędne zadania, umieszczone poniżej głównego zadania z którym są powiązane i *wcięte*."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +są powiązane. Tak więc ``Jaja``, ``Boczek`` i ``Pomidory`` są oczywiście
"oczywiście" →"na pierwszy rzut oka"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +To nazywane jest *zagnieżdżeniem*. Używamy zagnieżdżeń do definiowania bloków
Nazywamy to *zagnieżdżaniem*. Zagnieżdżania używamy do definiowania bloków kodu w ten oto sposób:

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Linia ``while running_time() < 10 000:`` sprawdza czy czas pracy urządzenia
"10000" — python nie zezwala na spacje w literałach liczbowych

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +miejsce gdzie możemy zobaczyć skalę działania*, to zostanie wyświetlony
"i tu widzimy działanie zagnieżdżania"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +``Image.ASLEEP``. Zauważ jak to jest wcięte poniżej instrukcji ``while``
Zwróć uwagę na wcięcie kodu po poleceniu ``while`` — takie jak w naszej liście zadań.

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +kodu pętli ``while``. Wygląda na to, że twoje urządzenie śpi przez 10 sekund
Będzie to sprawiać wrażenie, że

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +zanim obudzi się z zaskoczoną miną na swojej twarzy.
"z zaskoczeniem na twarzy."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Ogsługa zdarzenia
Obsługa

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Wypróbuj to!
Spróbuj sam!

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +powinniśmy zdarzenie to umieścić w nieskończonej pętli i sprawdzać czy przycisk
"to powinniśmy" → "musimy"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +powinniśmy zdarzenie to umieścić w nieskończonej pętli i sprawdzać czy przycisk
Nie zdarzenie mamy umieścić, bo to bez sensu, tylko microbita. Może coś takiego:

", musimy wprowadzić go w nieskończoną pętlę i sprawdzać w niej czy przycisk jest wciśnięty (ang. ``is_pressed``).

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Zróbmy bardzo prostego cyber-zwierzaka. Jest on smutny, dopóki nie naciśniesz
elektroniczne zwierzątko?

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Zróbmy bardzo prostego cyber-zwierzaka. Jest on smutny, dopóki nie naciśniesz
gdy nie naciskasz

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +przycisku ``A``. Ale jeżeli naciśniesz przycisk ``B`` on umrze. (Zdaję sobię
"A gdy wcisniesz przycisk ``B``, umiera."

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Czy widzisz jak sprawdzamy jakie przyciski są wciśnięte? Użyliśmy ``if`` (ang. jeśli),
"Rozumiesz jak sprawdzić które przyciski są wciśnięte?"

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +To jest podobne do języka angielskiego!
Prawie jak po polsku!

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Jeżeli naciśniesz przycisk, to zwróci ``True``, w przeciwnym wypadku zwróci
Jeżeli przycisk jest wciśnięty, zwraca ``True``

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +``False``. Powyższy kod można przetłumaczyć jako "jeżeli i tylko wtedy gdy
Może użyj tych samych tłumaczeń, które wprowadziłeś powyżej?

"przez cały czas: jeśli przycisk A jest wciśnięty — pokazuj szczęśliwą twarz, jeśli jednak przycisk B jest wciśnięty — przerwij pętlę, a w pozostałych przypadkach pokaż smutną minę".

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +minę." Przerywamy wykonywanie pętli (zatrzymujemy uruchomiony w nieskończoność
Przerywamy pętlę — bądźmy konsekwentni w terminologii.

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +program) za pomocą instrukcji ``break``.
zatrzymujący działający przez cały czas program

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Na samym końcu, kiedy cyber-zwierzak nie żyje, czyścimy ekran metodą
czyścimy (ang. ``clear``) ekran.

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Czy możesz pomyśleć o sposobie, aby ta gra była mniej tragiczna? Jak chciałbyś
Wiesz jak uczynić tę grę mniej tragiczną?

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Czy możesz pomyśleć o sposobie, aby ta gra była mniej tragiczna? Jak chciałbyś
Jak sprawdziłabyś

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +sprawdzić, czy *oba* przyciski zostały naciśnięte? (Podpowiedź: Python ma
są wciśnięte

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +logiczne operatory  ``and``, ``or`` i ``not``, które umożliwiają sprawdzenie
operatory logiczne

2017-11-27 19:53 UTC, deshipu commented on docs/tutorials/buttons.rst
> +logiczne operatory  ``and``, ``or`` i ``not``, które umożliwiają sprawdzenie
może warto dać tu tłumaczenia tych słów, a przykład:

Python ma operatory logiczne "i" (ang. ``and``), "lub" (ang. ``or``) oraz "nie" (ang. ``not``), którymi można sprawdzić wiele warunków (wyrażeń, które mają wartość ``True`` lub ``False``).

2017-11-27 19:54 UTC, deshipu commented
Drugą część sprawdzę jutro, bo już mi się wszystko myli.

2017-11-27 20:27 UTC, deshipu commented
Zaraz, przecież hello już jest przetłumaczone?

2017-11-29 19:05 UTC, WojtekReu reviewed
Przesyłam zmiany zgodnie z uwagami.

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Jak dotychczas utworzyliśmy kod umożliwiający urządzeniu pokazywanie czegoś.
Poprawione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +zdarzenia. Zdarzenia i wszystkie dane jakie dostaje urządzenie nazywamy *wejściem*.
Poprawione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Najprostszym sposobem na dostarczenie informacji na wejściu są dwa przyciski na urządzeniu micro:bit,
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Cały skrypt jest uśpiony przez 10 000 milisekund (czyli 10 sekund) a po tym
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +pomysłów:
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +#. *Funkcja* ``sleep`` usypia microbit na pewną ilość milisekund. Jeżeli
poprawione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +#. Istnieje obiekt nazwany ``button_a`` i on pozwala ci pobrać wartość
Uprościłem tak jak zaproponowałeś.

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +*zagnieżdżenie* - programistyczny odpowiednik rosyjskiej lalki - matrioszka.
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Teraz, gdy Python wie już ile razy został wciśnięty przycisk, to przetworzy
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +W końcu Python wie, że ma wyświetlić przesuwający się tekst na ekranie::
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Może ci się wydawać, że to jest mnóstwo pracy ale MicroPython robi to
Poprawione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Często potrzebujesz aby program poczekał na jakieś zdarzenie. Aby uzyskać
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +naciśnięcie przycisku.
Mieliśmy czasami problemy z tłumaczeniem bardziej złożonych konstrukcji. Zamienione.

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Aby utworzyć pętle w Pythonie użyj słowa kluczowego ``while`` (ang. dopóki). To sprawdza czy
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +coś jest ``True`` (ang. prawdziwe). Jeżeli tak jest, to uruchamia *blok kodu* zwany *zawartością*
Zamieniłem

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +a wtedy wykona się pozostała część kodu.
Zamieniam na twoją propozycję oraz to co jest w nawiasie na "ignorując ciało pętli"

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +zrobienia napisaną na kartce papieru. Pewnie będzie wyglądało to tak::
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +        Wyjmij drabinę z sąsiednich drzwi
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +To oczywiste, że główne zadania są podzielone na podrzędne zadania, które
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +zaczynają się od *akapitu* (wcięcie) (ang. indent) poniżej głównego zadania, do którego
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +są powiązane. Tak więc ``Jaja``, ``Boczek`` i ``Pomidory`` są oczywiście
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +To nazywane jest *zagnieżdżeniem*. Używamy zagnieżdżeń do definiowania bloków
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Linia ``while running_time() < 10 000:`` sprawdza czy czas pracy urządzenia
Poprawione - nie pamiętam dlaczego tak napisałem.

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +miejsce gdzie możemy zobaczyć skalę działania*, to zostanie wyświetlony
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +``Image.ASLEEP``. Zauważ jak to jest wcięte poniżej instrukcji ``while``
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +kodu pętli ``while``. Wygląda na to, że twoje urządzenie śpi przez 10 sekund
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +zanim obudzi się z zaskoczoną miną na swojej twarzy.
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Wypróbuj to!
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Ogsługa zdarzenia
Poprawione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +powinniśmy zdarzenie to umieścić w nieskończonej pętli i sprawdzać czy przycisk
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Czy widzisz jak sprawdzamy jakie przyciski są wciśnięte? Użyliśmy ``if`` (ang. jeśli),
Zamieniłem i dodałem przecinek przed które

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +To jest podobne do języka angielskiego!
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Jeżeli naciśniesz przycisk, to zwróci ``True``, w przeciwnym wypadku zwróci
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +``False``. Powyższy kod można przetłumaczyć jako "jeżeli i tylko wtedy gdy
Ok, zamieniam, ale nie jestem przekonany do tego. Może zamiast "jest naciśnięty" powinno być "zostanie naciśnięty"?

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +minę." Przerywamy wykonywanie pętli (zatrzymujemy uruchomiony w nieskończoność
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +program) za pomocą instrukcji ``break``.
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Na samym końcu, kiedy cyber-zwierzak nie żyje, czyścimy ekran metodą
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +Czy możesz pomyśleć o sposobie, aby ta gra była mniej tragiczna? Jak chciałbyś
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +sprawdzić, czy *oba* przyciski zostały naciśnięte? (Podpowiedź: Python ma
Zamienione

2017-11-29 19:05 UTC, WojtekReu commented on docs/tutorials/buttons.rst
> +logiczne operatory  ``and``, ``or`` i ``not``, które umożliwiają sprawdzenie
Zamienione

2017-11-29 20:47 UTC, deshipu requested changes
Dziękuję za zmiany, jest prawie dobrze, jeszcze ukryło się kilka drobiazgów.

2017-11-29 20:47 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Chociaż ten skrypt jest bezużyteczny, to jednak pokazuje name kilka ciekawych
nam

2017-11-29 20:47 UTC, deshipu commented on docs/tutorials/buttons.rst
> +"string" ~ przetwarza wszystko na ciąg znaków).
Tutaj jest trochę niejasno. Odbiegłbym od oryginału i zamknął nawias wcześniej, coś w rodzaju:

za pomocą funkcji ``str`` (skrót od angielskiego słowa "string"), która przetwarza wszystko na ciąg znaków.

2017-11-29 20:47 UTC, deshipu commented on docs/tutorials/buttons.rst
> +naciśnięcie przycisku.
Tutaj jest nadal niegramatycznie. Poprzedni komentarz nadal w mocy.

2017-11-29 20:47 UTC, deshipu commented on docs/tutorials/buttons.rst
> +Zróbmy bardzo proste elektroniczne zwierzątko. Jest on smutny, gdy nie naciskasz
Jest ono smutne

2017-11-29 20:47 UTC, deshipu commented on docs/tutorials/buttons.rst
> +pomocą instrukcji ``break``.
(ang. przerwij)

2017-11-30 15:10 UTC, deshipu commented on docs/tutorials/buttons.rst
> +sposób zareagować na oczekiwane zdarzenie takie jak naciśnięcie przycisku.
Poprzednia wersja była lepsza, moim zdaniem.

Po pierwsze "aby uzyskać to" chyba nie jest za bardzo po polsku, jest kalką słowo w słowo z szyku zdania po angielsku i brzmi dziwnie. Po drugie, najpierw mówimy o kodzie, potem o pętli, i potem nagle znowu o kodzie — trudno się to czyta, mimo, że mają różne rodzaje. Zamienienie miejscami pętli i kodu powoduje, że nie przeskakujemy tak.

2017-11-30 15:45 UTC, deshipu approved these changes

2017-11-30 15:46 UTC, merged